<?php

namespace UserStoriesBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function returnGroups($id){
        $em = $this->getEntityManager();
        $groups = $em->createQuery('SELECT g FROM UserStoriesBundle:Groups AS g LEFT JOIN UserStoriesBundle:User AS u
                       WITH g.id = u.groups.id WHERE u.id=:id')->setParameter(':id', $id)->getResult();
        return $groups;
    }
    
}
